### PR TITLE
Bump to Decidim v0.24.0

### PR DESCRIPTION
**Pull request by davefrey**

### CODE REVIEW

**Comment by davefrey** [comment]
Closes #68 
Coordinate with coming PR on liquidvotingio/liquid-decidim-demo

**Comment by oliverbarnes** [comment]
Rubocop is acting up on the build. Besides that, did you diff the proposals module v0.24.0.rc2 > v0.24 to check for any changes between the two versions?

**Comment by oliverbarnes** [comment]
Here's the changelog: https://github.com/decidim/decidim/releases/tag/v0.24.0

**Review by oliverbarnes — CHANGES_REQUESTED** [review]
As per my last two comments

**Comment by davefrey** [comment]
Thanks for the changelog and the reminder to compare...I'm mostly through that, and otherwise all specs and the demo app are running well, I'll ping here when the compare is finished.

**Comment by oliverbarnes** [comment]
Is this draft, then?

**Comment by davefrey** [comment]
I've read through the release notes; 60 of 430 issues mention proposals, but I think rather than reading them all, we should just protect ourselves as described in #90.

I'm opening this for review and merge, as well as liquidvotingio/liquid-decidim-demo#14

**Comment by oliverbarnes** [comment]
So no changes in the overriden files since v0.24.0rc2? 

Just want to be sure the latter were diffed with the their counterparts in v0.24.0 decidim-proposals. Or at that at least git logs for the latter show only commits before or at v0.24.rc2 - it's hard to tell from the update above 😄

**Comment by davefrey** [comment]
I confirm I've also compared files with decidim, specs and manual testing are green. CI green.

**Review by oliverbarnes — APPROVED** [review]

**Pull request merged**
