### PR TITLE
Enable assembly proposals and liquidvoting delegation of support

### PR DESCRIPTION
**Pull request by davefrey**
I've added the routes blindly from memory; I haven't been able to test yet because I don't have assembly/component/proposal/something data set in a way that renders the Support button on the Assembly Proposal page.

I do however see Liquidvoting api calls in the log file (for support/delegation context), so I anticipate LV is fine once Supports are rendering.

Related to #43

### CODE REVIEW

**Comment by oliverbarnes** [comment]
I've set this PR to draft until it's tested manually and programmatically with assemblies data. So @jinjagit, you're not reviewing this as much as collaborating :)

**Comment by jinjagit** [comment]
Quick manual test, using only 1 user = appears to work. Needs further manual testing (with chain of delegations, etc.):
assembly_proposal

To re-create the proposal for an assembly (as I did for this test):

1. Create an assembly (remember image files needed)
2. Add Proposals component to assembly (remember to select 'Supports enabled' & 'Proposal creation enabled')
3. Publish component
4. Publish assembly (I always 'Update' first, but maybe not needed)
5. Create proposal for assembly
6. Visit proposal public page.

**Review by jinjagit — CHANGES_REQUESTED** [review]
LGTM so far, but needs the specs mentioned by @oliverbarnes - I can work with you on this, if you like (I found some notes from our previous attempts)

**Review by jinjagit — COMMENTED** [review]
This now looks ready to merge (to me).  

I've added the specs we wanted + tested by commenting out the `assembly_proposal_delegation_path` in `engine.rb` (== assembly tests fail).  

I've also manually tested, by following the examples shown in the [demo vid](https://www.youtube.com/watch?v=CDQFtRYUjAs).

**Review by jinjagit — APPROVED** [review]
Approving to clear my re-requested review

**Review by oliverbarnes — APPROVED** [review]
Good work @jinjagit and @davefrey 💪

**Pull request merged**
